version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - backend/.env
    depends_on:
      - db
    volumes:
    - backend:/usr/src/app
    user: "myuser"
  db:
    image: postgres:latest
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
volumes:
  backend:
